# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# Minimal configuration for getting started
language: "en-US"
reviews:
  profile: "assertive"
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  summary:
    prompt: |
      Generate a comprehensive pull request summary that includes all the important details.

      ## Type of Change
      - [ ] Bug Fix (non-breaking change which fixes an issue)
      - [ ] New Feature (non-breaking change which adds functionality)
      - [ ] Breaking Change (fix or epic that causes existing functionality to change)
      - [ ] Architecture Enhancements (non-breaking change which refactors existing functionality)
